<a href="https://colab.research.google.com/github/EdgaRojas/MachineLearning/blob/main/Unidad%203/proyecto/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROYECTO UNIDAD 3
# KNN
## Alumno: Edgar Manuel Rojas Gurrola


In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Importamos librerias necesarias para knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve

In [19]:

prestamos_df = pd.read_csv('prestamos_ok.csv')
prestamos_df.head()


Unnamed: 0  loan_amnt  funded_amnt  funded_amnt_inv       term  int_rate  \
0           0       2400         2400           2400.0  36 months     15.96   
1           1      10000        10000          10000.0  36 months     13.49   
2           2       3000         3000           3000.0  36 months     18.64   
3           3       5600         5600           5600.0  60 months     21.28   
4           4       5375         5375           5350.0  60 months     12.69   

   installment grade sub_grade            emp_title  ... disbursement_method  \
0        84.33     C        C5                  NaN  ...                Cash   
1       339.31     C        C1  AIR RESOURCES BOARD  ...                Cash   
2       109.43     E        E1      MKC Accounting   ...                Cash   
3       152.39     F        F2                  NaN  ...                Cash   
4       121.45     B        B5            Starbucks  ...                Cash   

  debt_settlement_flag  debt_settlement_flag_date issue_year repaid  \
0                    N                        NaN       2011      1   
1                    N                        NaN       2011      1   
2                    N                        NaN       2011      1   
3                    N                        NaN       2011      0   
4                    N                        NaN       2011      0   

  loan_term_year purpose_code home_ownership_code grade_code addr_state_code  
0              3           11                   4          2               2  
1              3            9                   4          2               0  
2              3            0                   4          4               0  
3              5           11                   3          5               0  
4              5            9                   4          1               5  

[5 rows x 66 columns]

In [20]:
X = prestamos_df[['int_rate', 'loan_amnt','funded_amnt', 'annual_inc', 'dti', 'grade_code',
                 'revol_util']]

# Variable objetivo o variable a predecir
y = prestamos_df["repaid"]

Se eligen estas variables porque despues de observar la tabla de mayor importancia de cada variable decidi utilizar las primeras

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)
print("Dimensiones de X_train:", X_train.shape)
print("Dimensiones de X_test:", X_test.shape)

Dimensiones de X_train: (13935, 27)
Dimensiones de X_test: (5973, 27)


In [27]:
y_pred = knn1.predict(X_test)
print("Reporte de Clasificación:\n", classification_report(y_test, y_pred))
print("Matriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.18      0.16      0.17       930
           1       0.85      0.87      0.86      5043

    accuracy                           0.76      5973
   macro avg       0.52      0.51      0.52      5973
weighted avg       0.75      0.76      0.75      5973

Matriz de Confusión:
 [[ 150  780]
 [ 666 4377]]


In [29]:
import collections
from imblearn.over_sampling import SMOTE

print('Distribución de clases antes del oversampling (y_train): %s' % collections.Counter(y_train))

sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

print('Distribución de clases después del oversampling (y_train_res): %s' % collections.Counter(y_train_res))

Distribución de clases antes del oversampling (y_train): Counter({1: 11922, 0: 2013})
Distribución de clases después del oversampling (y_train_res): Counter({1: 11922, 0: 11922})


In [30]:
# Reentrenar el modelo KNN con los datos sobremuestreados
knn_resampled = KNeighborsClassifier(n_neighbors=1)
knn_resampled.fit(X_train_res, y_train_res)

print("Precisión del clasificador en fase de entrenamiento (después de oversampling):", knn_resampled.score(X_train_res, y_train_res))

Precisión del clasificador en fase de entrenamiento (después de oversampling): 1.0


In [32]:
# Evaluar el modelo reentrenado en el conjunto de prueba original
y_pred_resampled = knn_resampled.predict(X_test)

print("Reporte de Clasificación (después de oversampling):\n", classification_report(y_test, y_pred_resampled, target_names=["No Pagado", "Pagado"]))
print("Matriz de Confusión (después de oversampling):\n", confusion_matrix(y_test, y_pred_resampled))

Reporte de Clasificación (después de oversampling):
               precision    recall  f1-score   support

   No Pagado       0.16      0.24      0.20       930
      Pagado       0.85      0.78      0.81      5043

    accuracy                           0.69      5973
   macro avg       0.51      0.51      0.50      5973
weighted avg       0.74      0.69      0.71      5973

Matriz de Confusión (después de oversampling):
 [[ 224  706]
 [1134 3909]]


In [33]:
knn1 = KNeighborsClassifier(n_neighbors = 1)
knn1.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento:", knn1.score(X_train, y_train))

Precision del clasificador en fase de entrenamiento: 1.0


In [34]:

y_pred = knn1.predict(X_test)
print("\nReporte de métricas del clasificador con 1 vecino: \n",
      classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))

print(f'\nMatriz Confusion con 1 vecino:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 1 vecino: 
               precision    recall  f1-score   support

   No Pagado       0.18      0.16      0.17       930
      Pagado       0.85      0.87      0.86      5043

    accuracy                           0.76      5973
   macro avg       0.52      0.51      0.52      5973
weighted avg       0.75      0.76      0.75      5973


Matriz Confusion con 1 vecino:
 [[ 150  780]
 [ 666 4377]]


Se dectectan 150 impagos reales de 930

In [35]:

knn5 = KNeighborsClassifier(n_neighbors = 5)
knn5.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento", knn5.score(X_train, y_train) )


Precision del clasificador en fase de entrenamiento 0.8630785791173304


In [36]:

y_pred = knn5.predict(X_test)

print("\nReporte de métricas del clasificador con 5 vecinos: \n",
      classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'\nMatriz de Confusion con 5 vecinos:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 5 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.22      0.04      0.06       930
      Pagado       0.85      0.98      0.91      5043

    accuracy                           0.83      5973
   macro avg       0.53      0.51      0.48      5973
weighted avg       0.75      0.83      0.77      5973


Matriz de Confusion con 5 vecinos:
 [[  33  897]
 [ 120 4923]]


Se mejoro la precision de un 76% a un 83%
Solo detecta 33 impagos reales de 930

In [37]:

knn10 = KNeighborsClassifier(n_neighbors = 10)
knn10.fit(X_train, y_train)

print("Precision del clasificador en fase de entrenamiento", knn10.score(X_train, y_train) )


Precision del clasificador en fase de entrenamiento 0.8552565482597776


In [38]:

y_pred = knn10.predict(X_test)

print("\nReporte de métricas del clasificador con 10 vecinos: \n",
      classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))

print(f'Matriz de Confusion con 10 vecinos:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 10 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.32      0.02      0.04       930
      Pagado       0.85      0.99      0.91      5043

    accuracy                           0.84      5973
   macro avg       0.58      0.51      0.48      5973
weighted avg       0.76      0.84      0.78      5973

Matriz de Confusion con 10 vecinos:
 [[  20  910]
 [  43 5000]]


La precision aumento 1%
Solo detecta 20 impagos reales de 930

In [40]:
from sklearn.preprocessing import StandardScaler

X = prestamos_df[['int_rate', 'loan_amnt','funded_amnt', 'annual_inc', 'dti', 'grade_code',
                 'revol_util']]

y = prestamos_df["repaid"]

# Dividir Datos, stratify es para que mantenga la misma proporción de clases en ambos conjuntos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42, stratify=y)

# Normalizar variables (KNN es sensible a la escala)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Use StandardScaler para que el modelo KNN pudiera funcionar de manera óptima al calcular las distancias entre los vecinos.

In [41]:
# Entrenar KNN
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 3 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))

print ("\nMatriz de confusión con datos normalizados y 3 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")



Reporte de clasificación datos normalizados y 3 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.22      0.10      0.14      1177
      Pagado       0.86      0.93      0.89      6787

    accuracy                           0.81      7964
   macro avg       0.54      0.52      0.52      7964
weighted avg       0.76      0.81      0.78      7964


Matriz de confusión con datos normalizados y 3 vecinos:
 [[ 122 1055]
 [ 445 6342]] 



In [42]:
# Entrenar KNN
knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 5 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))

print ("\nMatriz de confusión con datos normalizados y 5 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")



Reporte de clasificación datos normalizados y 5 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.22      0.06      0.09      1177
      Pagado       0.86      0.96      0.91      6787

    accuracy                           0.83      7964
   macro avg       0.54      0.51      0.50      7964
weighted avg       0.76      0.83      0.79      7964


Matriz de confusión con datos normalizados y 5 vecinos:
 [[  69 1108]
 [ 239 6548]] 



In [43]:
# Entrenar KNN
knn_scaled = KNeighborsClassifier(n_neighbors=10)
knn_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 10 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))

print ("\nMatriz de confusión con datos normalizados y 10 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")



Reporte de clasificación datos normalizados y 10 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.29      0.04      0.08      1177
      Pagado       0.86      0.98      0.91      6787

    accuracy                           0.84      7964
   macro avg       0.57      0.51      0.50      7964
weighted avg       0.77      0.84      0.79      7964


Matriz de confusión con datos normalizados y 10 vecinos:
 [[  52 1125]
 [ 128 6659]] 



- El algoritmo lo que hace es comparar variables de cada dato con otros parecidos y de esa manera identificar si esa persona pagara o no.
- Ventajas: Es flexible, simple e intuitivo
- Limitaciones: Es lento con grandes cantidades de datos, es necesario normalizar datos para mejor funcionamiento
- El modelo aun no detecta
bien los no pagados
- Mejorar la eleccion de variables y normalizar los datos de esas variables