<a href="https://colab.research.google.com/github/EdgaRojas/MachineLearning/blob/main/Unidad%203/Practica5_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning y Deep Learning
## Unidad 3
## Practica 5: Random Forest Prestamos Lending Club

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Importamos librerias necesarias para Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve


In [2]:

prestamos_df = pd.read_csv('prestamos_ok.csv')
prestamos_df.head()

Unnamed: 0  loan_amnt  funded_amnt  funded_amnt_inv       term  int_rate  \
0           0       2400         2400           2400.0  36 months     15.96   
1           1      10000        10000          10000.0  36 months     13.49   
2           2       3000         3000           3000.0  36 months     18.64   
3           3       5600         5600           5600.0  60 months     21.28   
4           4       5375         5375           5350.0  60 months     12.69   

   installment grade sub_grade            emp_title  ... disbursement_method  \
0        84.33     C        C5                  NaN  ...                Cash   
1       339.31     C        C1  AIR RESOURCES BOARD  ...                Cash   
2       109.43     E        E1      MKC Accounting   ...                Cash   
3       152.39     F        F2                  NaN  ...                Cash   
4       121.45     B        B5            Starbucks  ...                Cash   

  debt_settlement_flag  debt_settlement_flag_date issue_year repaid  \
0                    N                        NaN     2011.0    1.0   
1                    N                        NaN     2011.0    1.0   
2                    N                        NaN     2011.0    1.0   
3                    N                        NaN     2011.0    0.0   
4                    N                        NaN     2011.0    0.0   

  loan_term_year purpose_code home_ownership_code grade_code addr_state_code  
0            3.0         11.0                 4.0        2.0             2.0  
1            3.0          9.0                 4.0        2.0             0.0  
2            3.0          0.0                 4.0        4.0             0.0  
3            5.0         11.0                 3.0        5.0             0.0  
4            5.0          9.0                 4.0        1.0             5.0  

[5 rows x 66 columns]

In [3]:
X = prestamos_df[['funded_amnt', "int_rate", "grade_code", 'purpose_code', 'addr_state_code',
                 'home_ownership_code', 'annual_inc', 'dti', 'revol_util',
                 'pub_rec_bankruptcies']]

# Variable objetivo o variable a predecir
y = prestamos_df["repaid"]


In [5]:
y_cleaned = y.dropna()
X_cleaned = X.loc[y_cleaned.index]

# Dividimos el dataFrame
# stratify es para que mantenga la misma proporción de clases en ambos conjuntos
X_train, X_test, y_train, y_test = train_test_split(X_cleaned, y_cleaned, random_state=42, test_size= 0.4, stratify=y_cleaned )

In [6]:
# verificamos la cantidad de registros asignados al dataframe de entrenamiento
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3357, 10), (2239, 10), (3357,), (2239,))

In [7]:
# Create Regressor with default properties
rfc1 = RandomForestClassifier(random_state=23)

# Fit estimator and display score
rfc1 = rfc1.fit(X_train, y_train)

# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", rfc1.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 1.0


In [8]:
# Realizar una prediccion con los datos de prueba
y_pred = rfc1.predict(X_test)

# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte del clasificador Random Forest sin balanceo de clases : \n",
      classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))

print(f'\nMatriz de Confusion Random Forest sin balanceo de clases:\n', confusion_matrix(y_test, y_pred ))


Reporte del clasificador Random Forest sin balanceo de clases : 
               precision    recall  f1-score   support

   No Pagado       0.28      0.03      0.06       351
      Pagado       0.85      0.98      0.91      1888

    accuracy                           0.83      2239
   macro avg       0.56      0.51      0.49      2239
weighted avg       0.76      0.83      0.78      2239


Matriz de Confusion Random Forest sin balanceo de clases:
 [[  12  339]
 [  31 1857]]


In [9]:

rfc2 = RandomForestClassifier(class_weight='balanced', random_state=23)
rfc2 = rfc2.fit(X_train, y_train)
y_pred = rfc2.predict(X_test)

print("Reporte del clasificador con balanceo de clases: \n", classification_report(y_test, y_pred,
                                                            target_names=["No Pagado", "Pagado"] ))
print('Matriz de Confusion con balanceo de clases \n' , confusion_matrix(y_test, y_pred))


Reporte del clasificador con balanceo de clases: 
               precision    recall  f1-score   support

   No Pagado       0.33      0.03      0.05       351
      Pagado       0.85      0.99      0.91      1888

    accuracy                           0.84      2239
   macro avg       0.59      0.51      0.48      2239
weighted avg       0.77      0.84      0.78      2239

Matriz de Confusion con balanceo de clases 
 [[   9  342]
 [  18 1870]]


In [10]:

rfc3 = RandomForestClassifier(n_estimators=200, max_depth=7, class_weight='balanced', random_state=23)

# Fit estimator and display score
rfc3 = rfc3.fit(X_train, y_train)

y_pred = rfc3.predict(X_test)

print("Reporte del clasificador con balanceo de clases n_estimators=200, max_depth=7: \n",
                   classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print('Matriz de Confusion con balanceo de clases n_estimators=200, max_depth=7\n' , confusion_matrix(y_test, y_pred))

Reporte del clasificador con balanceo de clases n_estimators=200, max_depth=7: 
               precision    recall  f1-score   support

   No Pagado       0.27      0.46      0.34       351
      Pagado       0.88      0.77      0.82      1888

    accuracy                           0.72      2239
   macro avg       0.58      0.61      0.58      2239
weighted avg       0.79      0.72      0.75      2239

Matriz de Confusion con balanceo de clases n_estimators=200, max_depth=7
 [[ 161  190]
 [ 438 1450]]


In [11]:

rfc4 = RandomForestClassifier(n_estimators=200, max_depth=10, class_weight='balanced', random_state=23)

# Fit estimator and display score
rfc4 = rfc4.fit(X_train, y_train)

y_pred = rfc4.predict(X_test)

print("Reporte del clasificador con balanceo de clases n_estimators=200, max_depth=10: \n",
                      classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print('Matriz de Confusion con balanceo de clases n_estimators=200, max_depth=10\n' , confusion_matrix(y_test, y_pred))

Reporte del clasificador con balanceo de clases n_estimators=200, max_depth=10: 
               precision    recall  f1-score   support

   No Pagado       0.30      0.25      0.28       351
      Pagado       0.87      0.89      0.88      1888

    accuracy                           0.79      2239
   macro avg       0.58      0.57      0.58      2239
weighted avg       0.78      0.79      0.78      2239

Matriz de Confusion con balanceo de clases n_estimators=200, max_depth=10
 [[  89  262]
 [ 204 1684]]


In [12]:
# ==========================================
# Gráfica de radar - Random Forest (Plotly)
# ==========================================
import plotly.graph_objects as go

# --- Nombres de los modelos ---
modelos = [
    "RF sin balanceo",
    "RF balanceado",
    "RF bal. n=200, depth=7",
    "RF bal. n=200, depth=10"
]

# --- Métricas reales ---
accuracy = [0.85, 0.85, 0.65, 0.73]
recall_no_pagado = [0.03, 0.01, 0.58, 0.40]
recall_pagado = [0.99, 1.00, 0.66, 0.78]
f1_macro = [0.49, 0.47, 0.54, 0.57]

# --- Ejes ---
metricas = ["Accuracy", "Recall No Pagado", "Recall Pagado", "F1 Macro"]

# --- Crear la figura ---
fig = go.Figure()

# Agregar cada modelo al radar
for i, modelo in enumerate(modelos):
    fig.add_trace(go.Scatterpolar(
        r=[accuracy[i], recall_no_pagado[i], recall_pagado[i], f1_macro[i], accuracy[i]],
        theta=metricas + [metricas[0]],
        fill='toself',
        name=modelo
    ))

# --- Personalización ---
fig.update_layout(
    title="Comparación de modelos Random Forest (Radar Plot)",
    polar=dict(
        radialaxis=dict(visible=True, range=[0, 1], tickvals=[0.2, 0.4, 0.6, 0.8, 1.0]),
    ),
    showlegend=True
)
fig.update_layout(width=800, height=600)
fig.show()


In [13]:

# Búsqueda de hiperparámetros con GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Iniciamos con un Modelo base con balanceo de clases (para compensar desbalance)
rf = RandomForestClassifier(class_weight='balanced', random_state=42)

# --- Definimos el espacio de búsqueda ---
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 7, 10 ],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

# --- Configuración de GridSearchCV ---
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring='f1_macro',   # Se puede cambiar a 'recall_macro', 'accuracy', etc.
    cv=3,                 # 3 particiones para validación cruzada
    n_jobs=-1,            # usa todos los núcleos disponibles
    verbose=2             # para ver el progreso
)

# --- Ejecutar búsqueda ---
grid_search.fit(X_train, y_train)

# --- Mostrar los mejores parámetros ---
print("Mejores hiperparámetros encontrados:")
print(grid_search.best_params_)

print("\n Mejor puntaje promedio (validación cruzada):")
print(grid_search.best_score_)

# --- Entrenar modelo final con los mejores parámetros ---
best_rf = grid_search.best_estimator_
y_pred_best = best_rf.predict(X_test)

# --- Evaluar en conjunto de prueba ---
print("\n Reporte de Clasificación (modelo óptimo):")
print(classification_report(y_test, y_pred_best, target_names=["No Pagado", "Pagado"]))

print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred_best))


Fitting 3 folds for each of 162 candidates, totalling 486 fits
Mejores hiperparámetros encontrados:
{'max_depth': 7, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 300}

 Mejor puntaje promedio (validación cruzada):
0.5870608675691654

 Reporte de Clasificación (modelo óptimo):
              precision    recall  f1-score   support

   No Pagado       0.26      0.46      0.34       351
      Pagado       0.88      0.76      0.82      1888

    accuracy                           0.71      2239
   macro avg       0.57      0.61      0.58      2239
weighted avg       0.79      0.71      0.74      2239

Matriz de Confusión:
[[ 163  188]
 [ 457 1431]]
